# Generated by Django 3.2.8 on 2021-10-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалить')),
                ('create_date', models.DateField(default='2021-10-26', verbose_name='Дата создания')),
            ],
        ),
    ]
