# Generated by Django 3.2.8 on 2021-11-05 02:48

from django.db import migrations, models
import django.db.models.deletion
import src.Announcements.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
                ('category', models.CharField(choices=[('Та', 'Танк'), ('Хи', 'Хил'), ('ДД', 'Демедж-Диллер'), ('То', 'Торговец'), ('ГМ', 'Гилдмастер'), ('Кв', 'Квестгивер'), ('Ку', 'Кузнец'), ('Ко', 'Кожевник'), ('Зе', 'Зельевар'), ('МЗ', 'Мастер заклинаний')], max_length=2, verbose_name='Категория')),
                ('create_date', models.DateTimeField(default='2021-11-05 02:48', editable=False, verbose_name='Дата и время создания')),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(max_length=255, upload_to=src.Announcements.models.announcement_picture_directory_path, verbose_name='Изображение')),
                ('create_date', models.DateTimeField(default='2021-11-05 02:48', editable=False, verbose_name='Дата и время создания')),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Сообщение')),
                ('accepted', models.BooleanField(default=False, verbose_name='Одобрен')),
                ('create_date', models.DateTimeField(default='2021-11-05 02:48', editable=False, verbose_name='Дата и время создания')),
                ('deleted', models.BooleanField(default=False)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='announcements.announcement', verbose_name='Относится к объявлению')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'ordering': ['-accepted'],
            },
        ),
    ]
