# Generated by Django 3.2.8 on 2021-11-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_auto_20211105_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='create_date',
            field=models.DateTimeField(default='2021-11-05 03:07', editable=False, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='announcementpicture',
            name='create_date',
            field=models.DateTimeField(default='2021-11-05 03:07', editable=False, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='announcementresponse',
            name='create_date',
            field=models.DateTimeField(default='2021-11-05 03:07', editable=False, verbose_name='Дата и время создания'),
        ),
    ]
