# Generated by Django 3.2.8 on 2022-01-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_auto_20211105_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-create_date',), 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='announcementresponse',
            options={'ordering': ['-accepted', '-create_date'], 'verbose_name': 'Отклик', 'verbose_name_plural': 'Отклики'},
        ),
        migrations.AlterField(
            model_name='announcementresponse',
            name='accepted',
            field=models.BooleanField(null=True, verbose_name='Одобрен'),
        ),
    ]
