# Generated by Django 3.2.8 on 2021-11-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20211105_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='create_date',
            field=models.DateTimeField(default='2021-11-05 05:03', editable=False, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='create_date',
            field=models.DateField(default='2021-11-05 05:03', editable=False, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='create_date',
            field=models.DateTimeField(default='2021-11-05 05:03', editable=False, verbose_name='Дата и время создания'),
        ),
    ]
