# Generated by Django 3.2.8 on 2021-11-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_auto_20211105_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания'),
        ),
    ]
