# Generated by Django 3.2.8 on 2021-11-05 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_auto_20211105_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='join_date',
        ),
    ]
